import { useEffect, useState } from "react"
import { useNavigate, useParams } from "react-router-dom"
import { ArrowLeft, PackageSearch } from "lucide-react"
import { useAuth } from "../../context/AuthContext"
import { Button } from "../../components/ui/Button"
import { Card, CardContent } from "../../components/ui/Card"
import { Input } from "../../components/ui/Input"
import * as productService from "../../services/productService"
import * as orderService from "../../services/orderService"
import { formatCurrency } from "../../utils/format"

export default function WholesalerBulkOrder() {
  const { productId } = useParams(); const { user } = useAuth(); const navigate = useNavigate(); const [products, setProducts] = useState([]); const [selectedId, setSelectedId] = useState(productId || ""); const [quantity, setQuantity] = useState("100"); const [address, setAddress] = useState(user.location || ""); const [payment, setPayment] = useState("Cash on Delivery"); const [error, setError] = useState(""); const [saving, setSaving] = useState(false)
  useEffect(() => { productService.listProducts({ inStockOnly: true }).then((list) => { setProducts(list); if (!selectedId && list[0]) setSelectedId(list[0].id) }) }, [selectedId])
  const product = products.find((item) => item.id === selectedId)
  async function submit(event) { event.preventDefault(); const amount = Number(quantity); if (!product || amount < (product.minOrderQty || 1) || amount > product.quantity) { setError("Choose a quantity within the available stock and minimum order."); return } setSaving(true); try { const order = await orderService.createOrder({ buyerId: user.id, buyerName: user.name, buyerType: "wholesaler", farmerId: product.farmerId, farmerName: product.farmerName, items: [{ productId: product.id, name: product.name, quantity: amount, unit: product.unit, price: product.bulkPrice || product.price }], subtotal: amount * (product.bulkPrice || product.price), deliveryFee: 500, total: amount * (product.bulkPrice || product.price) + 500, paymentMethod: payment, address }); navigate(`/wholesaler/orders/${order.id}`) } catch (err) { setError(err.message) } finally { setSaving(false) } }
  return <div className="mx-auto max-w-3xl px-4 py-6 lg:px-8"><button type="button" onClick={() => navigate(-1)} className="mb-4 inline-flex items-center gap-1 text-sm font-medium text-muted-foreground hover:text-foreground"><ArrowLeft className="h-4 w-4" /> Back</button><h1 className="font-heading text-2xl font-semibold text-foreground">Bulk order desk</h1><p className="mt-1 text-sm text-muted-foreground">Place a large order at the farmer&apos;s bulk rate.</p><Card className="mt-6"><CardContent><form onSubmit={submit} className="flex flex-col gap-4"><label className="text-sm font-medium text-foreground">Product<select className="mt-1 block w-full rounded-lg border border-border bg-background px-3 py-2 text-sm" value={selectedId} onChange={(event) => setSelectedId(event.target.value)}>{products.map((item) => <option key={item.id} value={item.id}>{item.name} ({formatCurrency(item.bulkPrice || item.price)}/{item.unit})</option>)}</select></label><Input label="Quantity" type="number" min="1" value={quantity} onChange={(event) => setQuantity(event.target.value)} error={error} /><Input label="Delivery address" value={address} onChange={(event) => setAddress(event.target.value)} /><label className="text-sm font-medium text-foreground">Payment<select className="mt-1 block w-full rounded-lg border border-border bg-background px-3 py-2 text-sm" value={payment} onChange={(event) => setPayment(event.target.value)}><option>Cash on Delivery</option><option>UPI</option><option>Card</option></select></label><Button type="submit" isLoading={saving}><PackageSearch className="h-4 w-4" /> Place bulk order</Button></form></CardContent></Card></div>
}