import { useEffect, useState } from "react"
import { useNavigate, useParams } from "react-router-dom"
import { ArrowLeft, MapPin } from "lucide-react"
import { Card, CardContent } from "../../components/ui/Card"
import { LoadingSpinner } from "../../components/ui/LoadingSpinner"
import { OrderStatusBadge } from "../../components/orders/OrderStatusBadge"
import * as orderService from "../../services/orderService"
import { formatCurrency, formatDate } from "../../utils/format"

export default function WholesalerOrderDetail() { const { orderId } = useParams(); const navigate = useNavigate(); const [order, setOrder] = useState(null); useEffect(() => { orderService.getOrder(orderId).then(setOrder) }, [orderId]); if (!order) return <div className="flex min-h-[50vh] items-center justify-center"><LoadingSpinner size={32} /></div>; return <div className="mx-auto max-w-3xl px-4 py-6 lg:px-8"><button type="button" onClick={() => navigate("/wholesaler/orders")} className="mb-4 inline-flex items-center gap-1 text-sm font-medium text-muted-foreground"><ArrowLeft className="h-4 w-4" /> Back to orders</button><div className="flex items-start justify-between"><div><h1 className="font-heading text-2xl font-semibold text-foreground">{order.id}</h1><p className="mt-1 text-sm text-muted-foreground">Placed {formatDate(order.createdAt, { withTime: true })}</p></div><OrderStatusBadge status={order.status} /></div><Card className="mt-5"><CardContent><p className="text-xs text-muted-foreground">Delivery address</p><p className="mt-1 flex items-start gap-2 text-sm font-medium text-foreground"><MapPin className="h-4 w-4 shrink-0 text-muted-foreground" />{order.address}</p></CardContent></Card><Card className="mt-5"><CardContent><h2 className="font-heading font-semibold text-foreground">Items</h2>{order.items.map((item) => <div key={item.productId} className="flex justify-between border-b border-border py-3 text-sm"><span>{item.name} · {item.quantity} {item.unit}</span><strong>{formatCurrency(item.quantity * item.price)}</strong></div>)}<div className="mt-3 flex justify-between font-heading font-semibold text-foreground"><span>Total</span><span>{formatCurrency(order.total)}</span></div></CardContent></Card></div> }